CREATE DATABASE EmployeeDB;

 
--CREATE SCHEMA Employee;
--GO

CREATE TABLE Employee
(
	ID INT PRIMARY KEY IDENTITY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME  VARCHAR(255) NOT NULL, 
	SSN VARCHAR(255) NOT NULL,
	DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES Department(ID)
);

CREATE TABLE EmplDetails
(
	ID INT PRIMARY KEY, 
	EMPLOYEE_ID INT FOREIGN KEY REFERENCES Employee(ID),
	SALARY DECIMAL(5,2), 
	ADDRESS_1 VARCHAR (255), 
	ADDRESS_2 VARCHAR (255), 
	CITY VARCHAR (255), 
	STATE VARCHAR(255),
	COUNTRY VARCHAR(255) 
	
);

CREATE TABLE Department
(
	ID INT PRIMARY KEY, 
	NAME_DEPT VARCHAR (255), 
	LOCATION VARCHAR (255)
	
);